"""add missing protocol and zubehoer tables

Revision ID: 4f42fda21170
Revises: 20260307_0003
Create Date: 2026-03-08 05:58:28.429868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f42fda21170'
down_revision: Union[str, Sequence[str], None] = '20260307_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zubehoer_katalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategorie', sa.String(length=80), nullable=False),
    sa.Column('bezeichnung', sa.String(length=255), nullable=False),
    sa.Column('artikel_nr', sa.String(length=80), nullable=True),
    sa.Column('standard_preis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artikel_nr')
    )
    op.create_index(op.f('ix_zubehoer_katalog_id'), 'zubehoer_katalog', ['id'], unique=False)
    op.create_index(op.f('ix_zubehoer_katalog_kategorie'), 'zubehoer_katalog', ['kategorie'], unique=False)
    op.create_table('protokoll_kopfdaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protokoll_id', sa.Integer(), nullable=False),
    sa.Column('aufbautyp', sa.String(length=64), nullable=False),
    sa.Column('vertriebsgebiet', sa.String(length=128), nullable=False),
    sa.Column('projektleiter', sa.String(length=255), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['protokoll_id'], ['protokolle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protokoll_id')
    )
    op.create_index(op.f('ix_protokoll_kopfdaten_id'), 'protokoll_kopfdaten', ['id'], unique=False)
    op.create_table('zubehoer_auswahl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protokoll_id', sa.Integer(), nullable=False),
    sa.Column('katalog_id', sa.Integer(), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('einzelpreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kunden_beigestellt', sa.Boolean(), nullable=False),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['katalog_id'], ['zubehoer_katalog.id'], ),
    sa.ForeignKeyConstraint(['protokoll_id'], ['protokolle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zubehoer_auswahl_id'), 'zubehoer_auswahl', ['id'], unique=False)
    op.create_index(op.f('ix_zubehoer_auswahl_katalog_id'), 'zubehoer_auswahl', ['katalog_id'], unique=False)
    op.create_index(op.f('ix_zubehoer_auswahl_protokoll_id'), 'zubehoer_auswahl', ['protokoll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zubehoer_auswahl_protokoll_id'), table_name='zubehoer_auswahl')
    op.drop_index(op.f('ix_zubehoer_auswahl_katalog_id'), table_name='zubehoer_auswahl')
    op.drop_index(op.f('ix_zubehoer_auswahl_id'), table_name='zubehoer_auswahl')
    op.drop_table('zubehoer_auswahl')
    op.drop_index(op.f('ix_protokoll_kopfdaten_id'), table_name='protokoll_kopfdaten')
    op.drop_table('protokoll_kopfdaten')
    op.drop_index(op.f('ix_zubehoer_katalog_kategorie'), table_name='zubehoer_katalog')
    op.drop_index(op.f('ix_zubehoer_katalog_id'), table_name='zubehoer_katalog')
    op.drop_table('zubehoer_katalog')
    # ### end Alembic commands ###
